### ISSUE TITLE
[critical] custom page models are not intercepted

### ISSUE THREAD

**Issue by bnomei** [getkirby/kql#11]
https://github.com/getkirby/kql/blob/3a2f8860318f176e6f5bc2055ce0c81fa257f484/lib/Interceptor.php#L15

needs to check for `instance of` instead of plain class name.

**Comment by bnomei** [comment]
a `is_a($object, \Kirby\Cms\Page::class)` check would cover inheritance for page objects

**Comment by bastianallgeier** [comment]
✅
