### ISSUE TITLE
add an optional cache per query

### ISSUE THREAD

**Issue by bnomei** [getkirby/kql#13]
implemented via usual plugin cache. config via each query...

```json
{
    "query": "page('photography').children",
    "cache": {
       "key": "myquery-{{ page.id }}",
       "expire": 60
    },
    "select": {
...
```

**Comment by bastianallgeier** [comment]
Uhhh, that's a nice idea!

**Comment by lukasIO** [comment]
Just chiming in here, that I've been excited about kql for a while and super happy to see it reached 1.0.0.
A caching layer would be the last missing puzzle piece for me to consider it for bigger projects. 

Additionally I'd like to put an automatic cache option up for discussion, that would allow all incoming queries to be auto-cached. 
In my (rather naive) way of thinking I imagine that that kind of cache could be (also automagically) invalidated on relevant file changes.

**Comment by bastianallgeier** [comment]
@lukasIO with such a cache layer I don't see any problems to introduce a global option for it. Yes, such a cache would be automatically erased whenever something changes in the panel. But be aware that this could not automatically listen to changes in the file system. You would still need to purge the cache manually in such cases.

**Comment by distantnative** [comment]
Reading this, automatic caches seem to be rather complex (actually very much the same as automatically normal Kirby queries in the core). Should we maybe first just tackle manual caching?

**Comment by lukasbestle** [comment]
Even with manual caching we need to make sure that the cache cannot be controlled from the request for the mentioned reasons.

**Comment by distantnative** [comment]
Lukas and I talked a lot about the potential implementation of this. In the end, I think this is getting too complex and complicated and too niche the it would justify the benefit for most users. I'd vote to close this as not planned from the core team.
