### ISSUE TITLE
Plugin folder includes .git folder when installed via composer

### ISSUE THREAD

**Issue by renestalder** [getkirby/kql#17]
I noticed, in comparison to other plugins, that the kql plugin folder contains the repositories .git folder after installation via composer. Now, I think, composer doesn't have a dedicated way of excluding files, but there is probably a way to remove the git folder when installed via composer.

I'm facing deployment issues with the .git folder due to the different permissions on this folder which I can resolve forcefully removing it before deployment. But still, I am curious if it could be excluded.

**Comment by lukasbestle** [comment]
As there are no tagged releases of this plugin yet, Composer installs via Git by default. You can override this behavior like this:

```
composer install --prefer-dist
```

**Comment by renestalder** [comment]
That was it. Thanks for the hint.
