### ISSUE TITLE
Srcset with configs presets not working

### ISSUE THREAD

**Issue by chrispreisler** [getkirby/kql#2]
Hey guys,

I would like to query the srcset of an image file with a preset defined in the config. Unfortunately this is not working. When defining explicit size values it is working. Is this a bug or do I do something wrong.

```
images: {
  query: "structureItem.image.toFiles",
  select: {
    url: "file.url",
    thumbs: "file.srcset([300, 800, 1024])",
    thumbsNotWorking1: "file.srcset()",
    thumbsNotWorking2: "file.srcset('default')"
  }
}
```

I defined the preset like this:

```
'thumbs' => [
  'srcsets' => [
      'default' => [300, 800, 1024]
  ]
]
```

Thanks for your help.

Best regards
Chris

**Comment by bastianallgeier** [comment]
This is now fixed
