### ISSUE TITLE
Block/Layout fields return type confusion

### ISSUE THREAD

**Issue by igregson** [getkirby/kql#20]
I'm seeing block and layout fields returned as a string of the raw object. I'd have expected either a string of HTML or the raw object. 

What should the return type be for block and layout fields?

**Comment by bastianallgeier** [comment]
Blocks are not supported in KQL yet. I will add support asap.

**Comment by igregson** [comment]
> Blocks are not supported in KQL yet. I will add support asap.

@bastianallgeier Any updates on this? KQL not supporting blocks is becoming quite a blocker(!).

**Comment by bastianallgeier** [comment]
Sorry for the delay! It's finally here :) 

Blocks and layouts are now fully supported. 🎉

![Screenshot 2021-02-12 at 10 43 16](https://user-images.githubusercontent.com/24532/107754383-b0a6c580-6d21-11eb-92dd-12b90c651fa9.png)

![Screenshot 2021-02-12 at 10 39 26](https://user-images.githubusercontent.com/24532/107754375-ae446b80-6d21-11eb-956d-e036259478e1.png)
