### ISSUE TITLE
Add queries to get translations

### ISSUE THREAD

**Issue by renestalder** [getkirby/kql#21]
As previously asked in the [Kirby Forum](https://forum.getkirby.com/t/retrieving-all-translations-via-kirby-query-language-kql/20486), whether there is a way to get the translations via kql, it turned out, it is currently not possible.

Would be very cool if this could be added. Sadly, I just don't have a lot of knowledge with PHP so that I could easily contribute to that.

**Comment by bastianallgeier** [comment]
You can now run queries for translations. 

Here are a couple examples

```
query: kirby.translations
```

```
query: kirby.translations.find('de').author
```

```
query: kirby.translation('de').get('delete')
```

**Comment by renestalder** [comment]
Thanks, Bastian.
