### ISSUE TITLE
option to autoregister page/site/file-methods

### ISSUE THREAD

**Issue by bnomei** [getkirby/kql#22]
instead of having to create and manually manage interceptors (or disable them altogether) maybe just add an option to automatically register any page, site and file methods that kirby knows about based on its config and used plugins.

why? i use custom methods a lot and kql is pretty hard to use then.

**Comment by trickreich** [comment]
@bnomei You've got a workaround for custom methods?

**Comment by trickreich** [comment]
@bastianallgeier can you maybe give us a hint here?

**Comment by bnomei** [comment]
@trickreich i copied the plugin locally and added an option to the interceptors class to disable the interceptors like this…


```php
class Interceptor
{
    public static function replace($object)
    {
        if (! \option('getkirby.kql.interceptors', true)) {
            return $object;
        }

        $className = get_class($object);
//… other code
```

**Comment by bastianallgeier** [comment]
✅ They are not auto-registered, but you can allow-list them very easily. See the docs on develop/1.1.0-rc.1
