### ISSUE TITLE
Get full object of nested objects (related pages)

### ISSUE THREAD

**Issue by felixhagspiel** [getkirby/kql#24]
First of all thank you for the awesome plugin!

I have products that can have 1 related category. What I am trying to accomplish is to return all products including the categories headline.

I got this query:

```
 {
            query: "site",
            select: {
              title: "site.title",
              url: "site.url",
              products: {
                query: "page('products').children.listed",
                select: {
                  id: true,
                  title: true,
                  category: true
                }
              },
            }
          }
```

Which works fine, but it is only returning the category ID for the category value.

If I change `category: true` to `categoryHeadline: 'page.category.headline'` I get the following error:

```
 data: {
      status: 'error',
      message: 'The method "Kirby\\Cms\\Field::headline()" is not allowed in the API context',
      code: 403,
      exception: 'Kirby\\Exception\\PermissionException',
      key: 'error.permission',
      file: '/site/plugins/kql-main/src/Kql/Interceptors/Interceptor.php',
      line: 38,
      details: [],
      route: 'query'
    }
```

I am very new to KQL, is there something wrong with my approach? Or is pulling full related objects not possible with kql?

**Comment by felixhagspiel** [comment]
I found the solution here: https://forum.getkirby.com/t/how-to-create-related-pages-field-where-related-pages-would-be-selected-from-other-page-children/13721/3

Apparently I have to call the method `toPages` on the related page.

Full working query:

```
{
            query: "site",
            select: {
              title: "site.title",
              url: "site.url",
              products: {
                query: "page('products').children.listed",
                select: {
                  id: true,
                  title: true,
                  category: {
                      query: "page.category.toPages",
                      select: {
                          id: true,
                          headline: true,
                      }
                  }
                }
              },
            }
          }
```

**Comment by bastianallgeier** [comment]
Sorry that I wasn't able to help with this. I'm glad you found the solution. The general rule for KQL is that every query should be written in the same way you would fetch/work with stuff in templates. It's built on top of the same architecture.
