### ISSUE TITLE
[Headless] Question - Is this csrf-token protected?

### ISSUE THREAD

**Issue by eder13** [getkirby/kql#27]
Hello,

I would like to use the query language extension to effectively use Kirby as a headless REST CMS (seperated React frontend). The only problem I see is, that this query language is using POST Requests, and afaik kirby uses csrf protection and there seems to be no (safe) way to get the csrf-token on the frontend. 

But is it even csrf protected? 

PS: CSRF Protection would still be applied, but instead of Kirby I would integrate it into my backend API which would fetch the kirby cms data which is protected via basic auth so that only the backend api has access to kirby. 

Thanks in advance!
-eder

**Comment by lukasbestle** [comment]
KQL by default only allows queries that return data. Unless you enable additional methods, it is not possible to modify data. So KQL is not susceptible to CSRF attacks in its default configuration.
