### ISSUE TITLE
Pagination not working with "select"

### ISSUE THREAD

**Issue by parislettau** [getkirby/kql#28]
I am trying to use the pagination option to limit results.

I am able to do this provided that I do not use the "select" query.

Whenever I  use the select query, the pagination option are ignored and revert to default 100 limit.

I have used various queries, including this one below from the **Pagination** instructions. I get the same results: always a reversion to the default 100 limit.

Any ideas what is going wrong?

`query: "page('notes').children",
  pagination: {
    limit: 5,  
  },
  select: {
    title: "page.title"
  }
}, { auth });`

**Comment by niorad** [comment]
For me the same also doesn't work without the "select"-query.

**Comment by igregson** [comment]
I'm not able to get pagination to work _at all_, with or without the `select` property. Without any `select` property, all items are returned. With it, only the default 100 limit.

**Comment by bastianallgeier** [comment]
✅

**Comment by parislettau** [comment]
Adding to this discussion as the [Fix pagination issue](https://github.com/getkirby/kql/commit/c2e698e229b00efe1e4aa1231b5e49962e3e4d68)[fix](https://github.com/getkirby/kql/commit/c2e698e229b00efe1e4aa1231b5e49962e3e4d68) [28](https://github.com/getkirby/kql/issues/28) has caused a new issue for me in my next.js site (using KQL for headless CMS).

It produces this error for one of my pages, which I haven't been able to troubleshoot yet:

# Server Error

Error: Error serializing `.products` returned from `getStaticProps` in "/shop". Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

This error happened while generating the page. Any console logs will be displayed in the terminal window.

##### Call Stack

###### isSerializable

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/lib/is-serializable-props.js (30:19)

###### <unknown>

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/lib/is-serializable-props.js (37:66)

###### Array.every

<anonymous>

###### isSerializable

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/lib/is-serializable-props.js (34:39)

###### Object.isSerializableProps

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/lib/is-serializable-props.js (57:12)

###### Object.renderToHTML

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/server/render.js (498:93)

###### async doRender

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/server/base-server.js (855:38)

###### async

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/server/base-server.js (950:28)

###### async

file:///Users/parislettau/Sites/memo-next.js/node_modules/next/dist/server/response-cache.js (63:36)
