### ISSUE TITLE
Return null or undefined for missing values

### ISSUE THREAD

**Issue by errnesto** [getkirby/kql#30]
Now when I select a value that does not exist on an entry I get an empty string.
It would be nice to have the option to get `null` or `undefined` here.
I think this would make it easier to check for a null value than for an empty string.

Maybe there already is a way to do this via field methods that I'm not aware off?

**Comment by lukasbestle** [comment]
You can use `page.yourfield.value` to get the raw value. For fields that don't exist, this is `null`.

**Comment by bastianallgeier** [comment]
I think @lukasbestle reply should be working great.
