### ISSUE TITLE
[Docs] BasicAuth login only possible via email (instead of username)

### ISSUE THREAD

**Issue by mandrasch** [getkirby/kql#31]
Hi, just made my first steps connecting to the Kirby KQL endpoint.

The docs example states that we can connect via username and password (https://github.com/getkirby/kql#sending-post-requests).

```javascript
const auth = {
  username: "apiuser",
  password: "strong-secret-api-password"
};
```
When I try to connect via username I get the following response:

![image](https://user-images.githubusercontent.com/777278/164887591-a38c28e4-ad55-4cc1-b699-834eb2e6d2a1.png)

When I use the emailaddress of the API user, everything work's fine:

![image](https://user-images.githubusercontent.com/777278/164887614-1b223de9-c2b4-49e2-8c13-e47c217f3b96.png)

(ThunderClient plugin VSCode)

**Comment by bastianallgeier** [comment]
This should be covered with the latest cookbook article: https://getkirby.com/docs/cookbook/setup/headless-getting-started and the new auth option in 1.1.0

**Comment by mandrasch** [comment]
> This should be covered with the latest cookbook article: https://getkirby.com/docs/cookbook/setup/headless-getting-started and the new auth option in 1.1.0

Great article, but the important part is missing => a screenshot with the credentials example below "Set the user credentials under the Basic dropdown and ...". 

Also the api user example (https://github.com/getkirby/kql/issues/32) could be added below " I prefer to use a dedicated user account for the API.". 

Cheers!

**Comment by mandrasch** [comment]
PS: Just saw https://github.com/getkirby/kql/releases/tag/1.1.0-rc.1 and "New option to switch off authentication for KQL", great stuff! Nice! 🥳
