### ISSUE TITLE
[1.1.0-rc.1] data in response breaking change

### ISSUE THREAD

**Issue by scsskid** [getkirby/kql#35]
in [1.1.0-rc.1](https://github.com/getkirby/kql/releases/tag/1.1.0-rc.1) result is stored in

```
res.result
```

before it was

```
res.result.data
```

which is great, but should be documented in release notes

**Comment by johannschopplich** [comment]
In my opinion the response object is correct. The `data` key will be created alongside `pagination` if you have added a `pagination.limit` to your query.

Take this TypeScript interface as a readable representation on what will be returned:

```ts
interface KirbyQueryResponse<Pagination extends boolean = false> {
  code: number
  status: string
  result?: Pagination extends true ? {
    data: any
    pagination: {
      page: number
      pages: number
      offset: number
      limit: number
      total: number
    }
  } : any
}
```

If the `pagination` is added to the query, the response will be nested with `data`.
