### ISSUE TITLE
[3.8.0-rc.2] Trying to include `uuid` in response returns 403

### ISSUE THREAD

**Issue by igregson** [getkirby/kql#38]
_Note: I initially mentioned this issue [here in Discord](https://canary.discord.com/channels/525634039965679616/1024969033793146920/1025383673555587183)._

Example response object:

```json
{
	"status": "error",
	"message": "The method \"Kirby\\Cms\\Page::uuid()\" is not allowed in the API context",
	"code": 403,
	"exception": "Kirby\\Exception\\PermissionException",
	"key": "error.permission",
	"file": "\/site\/plugins\/kql\/src\/Kql\/Interceptors\/Interceptor.php",
	"line": 43,
	"details": [],
	"route": "query"
}
```

**Comment by igregson** [comment]
I've tried adding the following to my site config:

```php
'kql' => [
   'methods' => [
      'allowed' => ['Kirby\Cms\Page::uuid'],
   ],
],
```

That changes the error message to:

> Access to the class \"Kirby\\Uuid\\PageUuid\" is not supported

**Comment by igregson** [comment]
Thinking that maybe I need to explicitly allow that class, I tried this:

```php
'kql' => [
   'classes' => [
      'allowed' => ['Kirby\Uuid\PageUuid'],
   ],
   'methods' => [
      'allowed' => ['Kirby\Cms\Page::uuid'],
   ],
],
```

and am now getting a 500: 

```json
{
	"status": "error",
	"message": "The object \"Kirby\\Uuid\\PageUuid\" cannot be rendered. Try querying one of its methods instead.",
	"code": 500,
	"exception": "Exception",
	"key": null,
	"file": "\/site\/plugins\/kql\/src\/Kql\/Kql.php",
	"line": 107,
	"details": [],
	"route": "query"
}
```

**Comment by lukasbestle** [comment]
For the time being, you can use `page.uuid.toString`.

**Comment by bastianallgeier** [comment]
I just fixed it on develop. Could you give it a try with the version there? 

New supported methods: 

```
page.uuid
page.permalink
file.uuid
file.permalink
user.uuid
user.permalink
```

**Comment by igregson** [comment]
> I just fixed it on develop. Could you give it a try with the version there?

Yes, this is working. Thank you :)

Question: Is there any way to have the raw `uuid` returned, as it's stored in the content file (i.e. without `page://` or `file://`)?

**Comment by igregson** [comment]
> Is there any way to have the raw `uuid` returned, as it's stored in the content file (i.e. without `page://` or `file://` prefix)?

Just figured out the answer to this. Yes, it is, via `page.content.uuid`.

Will leave closing this to you all (not sure if you'd like to keep it open until the patch in develop is merged).

**Comment by bastianallgeier** [comment]
Yay, I think it's fine if we close it then.
