### ISSUE TITLE
Kirby 4 compatibility

### ISSUE THREAD

**Issue by marcomezzavilla** [getkirby/kql#49]
I tried KQL with Kirby 4 (alpha 5), but the output is always an error: `Access to the class \"Kirby\Content\Field\" is not supported`.
The same queries work as expected on Kirby 3.9.5.

—

Example of POST request:

```json
{
  "query": "page('home')",
  "select": {
    "title": "page.title"
  }
}
```

[❌](https://emojipedia.org/cross-mark/) Response:
```json
{
  "status":"error",
  "message":"Access to the class \"Kirby\\Content\\Field\" is not supported",
  "code":403,
  "exception":"Kirby\\Exception\\PermissionException",
  "key":"error.permission",
  "file":"Interceptor.php",
  "line":269,
  "details":[],
  "route":"query"
}
```

(Thanks so much for this essential plugin)

**Comment by bastianallgeier** [comment]
Ah, we changed the namespace for the Field class. It's now Kirby\Content\Field and that is not yet setup in the KQL allow list. Easy fix though.
