### ISSUE TITLE
what is the model being uses for exactly?

### ISSUE THREAD

**Issue by bnomei** [getkirby/kql#5]
https://github.com/getkirby/kql/blob/master/lib/Kql.php#L19

it is it the entry point for the query to drill down in objects? else its site()?

**Comment by bastianallgeier** [comment]
Sorry to pick this up so late, but I'm not entirely sure what you mean :)

**Comment by bnomei** [comment]
np. the code moved a bit... https://github.com/getkirby/kql/blob/556381615993f6c552a6494be841c6fe80dba36d/src/Kql/Kql.php#L70

as far as i remember i tried using the query method in **php** and wanted to figure out how to provide a json string and custom model but ended up with `site()` when my code forwarded `null` because of a failed query. 

```php
// instead of
$model = page('hockus');
KQL::query($query, $model);

// i should have done
$model = page('hockus');
if($model) {
    KQL::query($query, $model);
} else {
   // throw error
}

```

**Comment by bnomei** [comment]
i guess what confused me as well when i started working with KQL was that in the json the root `query` prop will end up as `$model` in php. but once the plugin has some wiki/docs i think it will be fine.
