### ISSUE TITLE
calling kirby and custom site methods

### ISSUE THREAD

**Issue by bnomei** [getkirby/kql#6]
calling `kirby.site` and custom method does not seem to work. examples:
`kirby.site.mailjetContactslists`

but does
`kirby.site.url`

i guess that is intended. but why can any custom page method/field be called but not on site-object?

**Comment by bnomei** [comment]
i will port them to collections for now
`kirby.collection('mailjetContactslists')`

**Comment by bastianallgeier** [comment]
I think we need a whitelist for such custom methods.

**Comment by bastianallgeier** [comment]
✅
