### ISSUE TITLE
Allow empty field values for certain methods

### ISSUE THREAD

**Issue by kms-rscholz** [getkirby/kql#9]
```
{
    "status": "error",
    "exception": "TypeError",
    "message": "Argument 1 passed to Kirby\\Text\\Markdown::parse() must be of the type string, null given, called in …/components.php on line 113",
    "file": "",
    "line": 64,
    "code": 500,
    "route": "query"
}
```

The error is caused by an empty field within a structure entry (caption for an image). It'd be great if the plugin would check for a valid value before a respective method is applied. In this case it is the `markdown` method. The field in question is not filled in for every structure entry, thus the error.

**Comment by bastianallgeier** [comment]
I'm afraid that the plugin itself cannot really handle all of such cases, but the particular one will be fixed in Kirby's core in 3.4
